improved testing and reporting of prerequisites

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,37 +1,60 @@
 #!/usr/bin/env bash
 
 declare GITHUB_BASE="https://github.com/cjungmann/lib"
+
+#############################
+### CUSTOMIZED TO PROJECT ###
+#############################
+
+# My libraries, cloned and built below if not installed
 declare -a LIBS_NEEDED=( argeater pager contools )
+
+# System resource prerequisites:
 declare -a LIBS_REQUIRED=(
     libncurses.so    libncurses-dev
 )
-
 declare -a HEADERS_REQUIRED=(
-    bash/builtins.h  bash-builtins
+    builtins.h  bash-builtins
 )
-
 declare -a APPS_REQUIRED=(
     soelim   man-db
 )
 
+#############################
+### END OF PROJECT CUSTOM ###
+#############################
+
+# Array to track missing prerequisites for final message
+declare -a PACKAGES_REQUIRED=()
+
+# Arrays to track Makefile updates:
 declare -a LIB_DIRS_ARRAY=()
 declare -a LIB_FLAGS_ARRAY=()
 declare -a LIB_MODULES_ARRAY=()
 declare -a INCFLAGS_ARRAY=()
 
-app_test() { type "$1" >/deb/null 2>&1; }
+app_test()
+{
+    type "$1" >/dev/null 2>&1
+    local -i ecode="$?"
+    return "$ecode"
+}
+
 lib_test()
 {
-    local -i count=$( /sbin/ldconfig -p | grep "$1" )
+    local -i count=$( /sbin/ldconfig -p | grep -c "$1" )
     (( count == 1 ))
 }
 
 header_test()
 {
-    mkfifo bogus.c
-    echo "#include <$1>; int main(void) { return 0; }" > bogus.c
-    gcc -x c bogus.c
+    printf $'#include <%s>\nint main(void)\n{ return 0; }\n' "$1" > bogus.c
+
+    local bi_pre=/usr/include/bash
+    local -a incs=( -I"$bi_pre" -I"$bi_pre"/include )
+    gcc -x c -fsyntax-only "${incs[@]}"  bogus.c >/dev/null 2>&1
     local -i ecode="$?"
+
     rm bogus.c
 
     [ "$ecode" -eq 0 ]
@@ -43,6 +66,9 @@ confirm_prereq()
     local cp_test_function="$2"
     local cp_prereq_type="$3"
 
+    # Nameref to update global variable
+    local -n cp_all=PACKAGES_REQUIRED
+
     local fmt=$'Missing %s \e[31;1m%s\e[39;22m. Please install \e[31;1m%s\e[39;22m.\n'
 
     local -i missing_count=0
@@ -53,8 +79,12 @@ confirm_prereq()
         else
             package="$el"
             if ! "$cp_test_function" "$prereq"; then
-                printf "$fmt" "$prereq" "$package"
+                # Give warning
+                printf "$fmt" "$cp_prereq_type" "$prereq" "$package"
+                # track missing count for function exit code
                 (( ++missing_count ))
+                # Accumulate missing packages for final message
+                cp_all+=( $package )
             fi
             prereq=""
             package=""
@@ -67,37 +97,18 @@ confirm_prereq()
 confirm_prerequisites()
 {
     local -i error_count=0
-    confirm_prereq "HEADERS_REQUIRED" "header_test" "header"
-    (( error_count += $? ))
     confirm_prereq "LIBS_REQUIRED" "lib_test" "library"
     (( error_count += $? ))
     confirm_prereq "APPS_REQUIRED" "app_test" "app"
     (( error_count += $? ))
-
+    confirm_prereq "HEADERS_REQUIRED" "header_test" "header"
+    (( error_count += $? ))
     (( error_count == 0 ))
 }
 
-confirm_devs()
-{
-    local -i missing_count=0
-    local header package
-    for el in "${DEVS_REQUIRED[@]}"; do
-        if [ -z "$header" ]; then
-            header="$el"
-        else
-            package="$el"
-            if ! [ -f "/usr/include/$header" ]; then
-                printf $'Cannot find header \e[31;1m%s\e[m.  Please install \e[31;1m%s\e[m.\n' \
-                       "$header" "$package"
-                (( ++missing_count ))
-            fi
-            header=
-            package=
-        fi
-    done
-
-    [ "$missing_count" -eq 0 ]
-}
+########################################################
+### Checking for and installing my missing libraries ###
+########################################################
 
 install_and_build_library()
 {
@@ -157,7 +168,6 @@ confirm_library()
     fi
 }
 
-
 setup_libraries()
 {
     for lib in "${LIBS_NEEDED[@]}"; do
@@ -165,11 +175,22 @@ setup_libraries()
     done
 }
 
+# This will identify/warn about missing libraries, with advice
+# on which package will remedy the omission:
 if ! confirm_prerequisites; then
+    echo "Use your package manager to install the following packages:"
+    echo "${PACKAGES_REQUIRED[*]}"
+    echo ""
+    echo "Hint: copy the list to paste into your install command."
     exit
 fi
 
+
+# This checks only for my libraries, cloning and installing as
+# as static library under this project if the library is not
+# installed globally:
 setup_libraries
+
 
 declare flags_str="s|LIB_FLAGS =.*|LIB_FLAGS = ${LIB_FLAGS_ARRAY[*]}|"
 declare mods_str="s|LIB_MODULES =.*|LIB_MODULES = ${LIB_MODULES_ARRAY[*]}|"
@@ -181,12 +202,11 @@ incflags_str="${incflags_str// /\\ }"
 printf $'flags_str with be \e[32;1m%s\e[m\n' "$flags_str"
 printf $'mods_str with be \e[32;1m%s\e[m\n' "$mods_str"
 printf $'incflags_str with be \e[32;1m%s\e[m\n' "$incflags_str"
-read -n1 -p "Press any key to update the Makefile"
 
 declare -a SED_LIB_ARGS=(
     -e "${flags_str}"
     -e "${mods_str}"
     -e "${incflags_str}"
-    )
+)
 
 sed -i "${SED_LIB_ARGS[@]}" Makefile
