Work on internal functions get_option_entries and parse_args, with complete rewrite of get_option_entries.
The old code was too complicated and hard to follow, hiding mistakes.
Now using better variable names and more obvious code.

diff --git a/pwb_sources.d/pwb_read_args b/pwb_sources.d/pwb_read_args
--- a/pwb_sources.d/pwb_read_args
+++ b/pwb_sources.d/pwb_read_args
@@ -33,7 +33,7 @@ pwb_read_args()
         if [ -z "$col_ital" ]; then col_ital=$'\e[32;1m'; fi
         local col_none=$'\e[m'
 
-        printf "\nUSAGE for $fname:\n"
+        printf "\nUSAGE for %s:\n" "$fname"
         printf "  %s" "$fname"
 
         local -i count_flags=0
@@ -88,84 +88,62 @@ pwb_read_args()
     # it's the name of the variable to set from the next argument.
     get_option_entries()
     {
-        # Clear goe_name as signal it shouldn't be changed,
-        # which might be because it is a flag whose value
-        # will have already been set upon return
-        local -n goe_rname="$1"
-        goe_rname=""
-
-        # Trim off leading '-' so chars can be considered individually
+        local -n goe_return="$1"
+        goe_return=""
+        # trim '-' prefix
         local option_progress="${2:1}"
 
-        local opt_flag
-        # For each option letter of the option arg, seek an options list match.
-        # Use remainder of option characters as the option value if the option
-        # takes an option value rather than used to set a flag:
+        local opt_el opt_token opt_variable
         while [ "${#option_progress}" -gt 0 ]; do
+            local progress_letter="${option_progress:0:1}"
 
-            # Search opts_list for matching option flag/name pair
-            for el in "${pa_opts_list[@]}"; do
-                # It's a two-part search, so the first time we just get
-                # the option letter, the following time through gets the
-                # target variable name
-                if [ -z "$opt_flag" ]; then
-                    opt_flag="$el"
+            # check rows in options list for match to progress_letter
+            for opt_el in "${pa_opts_list[@]}"; do
+                if [ -z "$opt_token" ]; then
+                    opt_token="$opt_el"
                     continue
-                # Second time through, we have enough to work
                 else
-                    # Save and clear opt_flag to permit break or continue
-                    local goe_opt_name="$opt_flag"
-                    opt_flag=""
+                    opt_variable="$opt_el"
+                fi
 
-                    # Compare first letters to find a match
-                    if [[ "${goe_opt_name:0:1}" == "${option_progress:0:1}" ]]; then
-                        # If the option is a flag (it's one char lone),
-                        # set it, update option_progress, and continue:
-                        if [ "${#goe_opt_name}" -eq 1 ]; then
-                            local -n tval="$el"
+                # Use the opt_list row if opt_token of opt_list_row matches current arg char:
+                local opt_letter="${opt_token:0:1}"
+                if [[ "$opt_letter" == "$progress_letter" ]]; then
+                    # advance the option_progress as soon as we make a match:
+                    # either we use the value, or continue to process the next
+                    # option_progress letter
+                    option_progress="${option_progress:1}"
 
-                            # Caller's reponsibility to clear values before calling:
-                            if (( tval != 0 )); then
-                                read -s -n1 -p "Variable '$el' should have been preset to 0"
-                                # Do not tolerate arguments mistakes committed by script
-                                # function caller:
-                                exit 1
-                            else
-                                tval=1
-                                # Remove matched flag char in order to process the next one
-                                option_progress="${option_progress:1}"
-                                # return to outer loop for next character
-                                continue 2
-                            fi
-                        # The option takes an value
+                    local -n tvar="$opt_variable"
+                    if [ "${#opt_token}" -gt 1 ]; then
+                        # option takes a value
+                        if [ "${#option_progress}" -gt 0 ]; then
+                            # if letter follow, they are the value
+                            tvar="$option_progress"
+                            return 0
                         else
-                            # If chars follow value-taking option, they are the value.
-                            # save the remainder directly to the target variable and leave
-                            #    just save the rest
-                            if [ "${#option_progress}" -gt 1  ]; then
-                                local -n tval="$el"
-                                tval="${option_progress:1}"
-                            # If the current char is the last, the value will be in the
-                            # next argument.  Return the variable name to be set with the
-                            # with the next argument:
-                            else
-                                goe_rname="$el"
-                            fi
-
-                            # break out of outer loop to finish early
-                            break 2
+                            # No following letters, return the variable name
+                            # for the calling function to use to set with the
+                            # next argument value:
+                            goe_return="$opt_variable"
+                            return 0
                         fi
-                        break
+                    else
+                        # Option is a flag, just set it and return
+                        tvar=1
+                        # Bypass failed with deep continue
+                        continue 2
                     fi
                 fi
+                # Setup to seek next opt_list pair:
+                opt_token=""
+                opt_variable=""
             done
 
-            if [ -z "$PWB_READ_ARGS_SILENTLY" ]; then
-                echo "Unrecognized option '-${option_progress:0:1}' from '$option_progress'"
-                exit 1
-            else
-                option_progress="${option_progress:1}"
-            fi
+            printf $'Unrecognized option \e[31;1m-%c\e[m.  Fix script to avoid this mistake.\n' "$progress_letter"
+            read -n1 -p "Press any key to exit"
+            exit 1
+
         done
     }
 
@@ -191,37 +169,33 @@ pwb_read_args()
 
         local -i args_index=0
         local -i args_count="${#pa_arg_names[@]}"
-        local opt_name
+        local var_name
         local -i clas_index=0
+
         for arg in "${pa_command_args[@]}"; do
             # If previous pass identified an option that sets a value,
-            # set the value and clear the opt_name variable.
-            if [ -n "$opt_name" ]; then
-                local -n tvar="$opt_name"
+            # set the value and clear the var_name variable.
+            if [ -n "$var_name" ]; then
+                local -n tvar="$var_name"
                 tvar="$arg"
-                opt_name=""
-            # '-' prefix starts option processing
-            # elif still_processing_options && [[ "$arg" =~ ^-..? ]]; then
-            elif still_processing_options && [[ "$arg" =~ ^-..? ]]; then
-                if [[ "$arg" == "--" ]]; then
-                    option_parsing=0
-                else
-                    # if 'opt_name' is set on return, opt_name is the variable
-                    # to set with the value of the next CL argument
-                    get_option_entries opt_name "$arg"
-                fi
-                # not an option, set next positional argument
-            elif (( args_index < args_count )); then
-                local argname="${pa_arg_names[$args_index]}"
-                local -n tvar="$argname"
-                tvar="$arg"
-                (( ++args_index ))
+                var_name=""
             else
-                continue # without discarding the argument
+                if still_processing_options && [[ "$arg" =~ ^-. ]]; then
+                    if [[ "$arg" == "--" ]]; then
+                        option_parsing=0
+                    else
+                        # if 'var_name' is set on return, var_name is the variable
+                        # to set with the value of the next CL argument
+                        get_option_entries var_name "$arg"
+                    fi
+                    # not an option, set next positional argument
+                elif (( args_index < args_count )); then
+                    var_name="${pa_arg_names[$(( args_index++ ))]}"
+                    local -n tvar="$var_name"
+                    tvar="$arg"
+                    var_name=""
+                fi
             fi
-
-            # Discard any consumed arguments
-            unset pa_command_args[$(( clas_index++ ))]
         done
     }
 
